# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from etrobo_grpc import etrobo_control_pb2 as etrobo__grpc_dot_etrobo__control__pb2


class EtRoboStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Control = channel.unary_unary(
                '/etrobo_grpc.EtRobo/Control',
                request_serializer=etrobo__grpc_dot_etrobo__control__pb2.ControlParameter.SerializeToString,
                response_deserializer=etrobo__grpc_dot_etrobo__control__pb2.ControlReply.FromString,
                )


class EtRoboServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Control(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EtRoboServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Control': grpc.unary_unary_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=etrobo__grpc_dot_etrobo__control__pb2.ControlParameter.FromString,
                    response_serializer=etrobo__grpc_dot_etrobo__control__pb2.ControlReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'etrobo_grpc.EtRobo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EtRobo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/etrobo_grpc.EtRobo/Control',
            etrobo__grpc_dot_etrobo__control__pb2.ControlParameter.SerializeToString,
            etrobo__grpc_dot_etrobo__control__pb2.ControlReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
