# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etrobo_grpc/etrobo_control.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='etrobo_grpc/etrobo_control.proto',
  package='etrobo_grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n etrobo_grpc/etrobo_control.proto\x12\x0b\x65trobo_grpc\"_\n\x10\x43ontrolParameter\x12\x0c\n\x04mode\x18\x01 \x01(\x05\x12\x0c\n\x04\x65\x64ge\x18\x02 \x01(\x05\x12\r\n\x05speed\x18\x03 \x01(\x11\x12\r\n\x05steer\x18\x04 \x01(\x11\x12\x11\n\tthreshold\x18\x05 \x01(\x11\"M\n\x0c\x43ontrolReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12,\n\x05param\x18\x02 \x01(\x0b\x32\x1d.etrobo_grpc.ControlParameter2O\n\x06\x45tRobo\x12\x45\n\x07\x43ontrol\x12\x1d.etrobo_grpc.ControlParameter\x1a\x19.etrobo_grpc.ControlReply\"\x00\x62\x06proto3'
)




_CONTROLPARAMETER = _descriptor.Descriptor(
  name='ControlParameter',
  full_name='etrobo_grpc.ControlParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='etrobo_grpc.ControlParameter.mode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge', full_name='etrobo_grpc.ControlParameter.edge', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='etrobo_grpc.ControlParameter.speed', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steer', full_name='etrobo_grpc.ControlParameter.steer', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='etrobo_grpc.ControlParameter.threshold', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=144,
)


_CONTROLREPLY = _descriptor.Descriptor(
  name='ControlReply',
  full_name='etrobo_grpc.ControlReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='etrobo_grpc.ControlReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param', full_name='etrobo_grpc.ControlReply.param', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=223,
)

_CONTROLREPLY.fields_by_name['param'].message_type = _CONTROLPARAMETER
DESCRIPTOR.message_types_by_name['ControlParameter'] = _CONTROLPARAMETER
DESCRIPTOR.message_types_by_name['ControlReply'] = _CONTROLREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlParameter = _reflection.GeneratedProtocolMessageType('ControlParameter', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLPARAMETER,
  '__module__' : 'etrobo_grpc.etrobo_control_pb2'
  # @@protoc_insertion_point(class_scope:etrobo_grpc.ControlParameter)
  })
_sym_db.RegisterMessage(ControlParameter)

ControlReply = _reflection.GeneratedProtocolMessageType('ControlReply', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLREPLY,
  '__module__' : 'etrobo_grpc.etrobo_control_pb2'
  # @@protoc_insertion_point(class_scope:etrobo_grpc.ControlReply)
  })
_sym_db.RegisterMessage(ControlReply)



_ETROBO = _descriptor.ServiceDescriptor(
  name='EtRobo',
  full_name='etrobo_grpc.EtRobo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=225,
  serialized_end=304,
  methods=[
  _descriptor.MethodDescriptor(
    name='Control',
    full_name='etrobo_grpc.EtRobo.Control',
    index=0,
    containing_service=None,
    input_type=_CONTROLPARAMETER,
    output_type=_CONTROLREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ETROBO)

DESCRIPTOR.services_by_name['EtRobo'] = _ETROBO

# @@protoc_insertion_point(module_scope)
